### ISSUE TITLE
Compilation errors while using Eigen 3.4

### ISSUE THREAD

**Issue by fredroy** [SofaDefrost/ModelOrderReduction#43]
FYI, while trying to make MOR compile with SOFA v21.12, I came across compilations problems involving Eigen API.

It appears that the latest Eigen version (3.4) has changed some stuff, and so MOR is not compatible with it.
When I downgraded to 3.3.8, it was compiling well.

**Comment by fredroy** [comment]
https://eigen.tuxfamily.org/index.php?title=3.4#Changes_that_might_break_existing_code

So the break came from the fact that the indices to access element in matrices was a floating type (MatrixXd so double)

**Comment by alxbilger** [comment]
Fixed by https://github.com/SofaDefrost/ModelOrderReduction/pull/44
